search_uris:
  - https://milwaukee.craigslist.org/search/sss?format=rss&query=loom&sort=rel&hasPic=1&search_distance=100&postal=53216
  - https://grandrapids.craigslist.org/search/sss?format=rss&query=loom&sort=rel&hasPic=1&search_distance=50&postal=49646
  - https://chicago.craigslist.org/search/sss?format=rss&query=loom&sort=rel&hasPic=1&search_distance=200&postal=60626

excluded_terms:
  - lloyd
  - art deco
  - american girl
  - spark plug
  - knitter
  - fruit
  - wire

sender: glen.smuda@gmail.com
recipient: gwen.smuda@gmail.com
delivery_method: sendmail
