category: Weaving Looms

search_terms:
  - weaving
  - loom

zip: 60641
search_radius: 200

cities:
  - grandrapids
  - chicago
  - milwaukee

excluded_terms:
  - lloyd
  - art deco
  - american girl
  - spark plug
  - knitter
  - fruit
  - wire
  - rainbow
  - mattress

sender: gwen.smuda@gmail.com
recipient: gwen.smuda@gmail.com
