category: Drum Heads
search_uris:
  - https://chicago.craigslist.org/search/sss?format=rss&query=remo+drum+heads&sort=rel&hasPic=1&search_distance=200&postal=60626

excluded_terms:
  - antifreeze

sender: gwen.smuda@gmail.com
recipient: gwen.smuda@gmail.com
delivery_method: sendmail
