category: Drums
search_uris:
  - https://chicago.craigslist.org/search/sss?format=rss&query=gretsch+drum&sort=rel&hasPic=1&search_distance=200&postal=60641

excluded_terms:
  - antifreeze

sender: gwen.smuda@gmail.com
recipient: gwen.smuda@gmail.com
